name: Deploy go application

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Chckout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: checking
        run: echo $PORT  
      - name: Build docker image
        run: docker build -t manafabdulc/todos .
      - name: Push image to dockerhub
        run: docker push manafabdulc/todos:latest    

  deploy:
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Delete running container
        run: docker rm -f $(docker ps -aq)
      - name: Delete all images
        run: docker rmi $(docker images -aq)  
      - name: pull the docker image
        run: docker pull manafabdulc/todos
      - name: Delete old container
        run: docker rm -f todos
      - name: Create folder for volume 
        run: sudo mkdir -p /mnt/psql
      - name: Remove postgres db
        run: docker rm -f postgres-container
      - name: remove previous network
        run: docker network rm my-network  
      - name: Create network
        run: docker network create my-network        
      - name: Run db container 
        run:  docker run --name postgres-container --network my-network -e POSTGRES_USER=${{secrets.DB_USER}} -e POSTGRES_PASSWORD=${{secrets.DB_PASSWORD}} -e POSTGRES_DB=${{secrets.DB_NAME}} -v /mnt/psql:/var/lib/postgresql/data -p 5432:5432 -d postgres:16-alpine3.20
      - name: run application image
        run: docker run --name todos --network my-network -e PORT=${{ secrets.PORT }} -e DB_URL=${{ secrets.DB_URL }} -p ${{ secrets.PORT }}:${{ secrets.PORT }} -d manafabdulc/todos  
          
